mc_qq_ws_server: true
mc_qq_ws_url: /minecraft/ws
mc_qq_ws_port: 8080
mc_qq_ws_password: ""
mc_qq_send_group_name: true
mc_qq_display_server_name: true
mc_qq_say_way: 说：
mc_qq_chat_image_enable: false
mc_qq_server_list: []
debug_mode: false
